### ISSUE TITLE
Questions about the input size and out put size of the CNN model

### ISSUE THREAD

**Issue by LeopoldPu** [jouvetg/dle#1]
Hello, I have a question about the model. While reviewing the code, I noticed that during training, the model's input size is (32, 32, 3) and its output size is (32, 32, 2). However, during testing, the input size is (185, 121, 3) and the output size is (185, 121, 2). I'm unsure why the trained CNN model can handle different input and output sizes. Any feedback you can provide would be greatly appreciated. Thank you!

**Comment by jouvetg** [comment]
hello, sorry for my long reply, these CNN will return the size you give in input. This CNN can handle different sizes simply because CNN are local operations (on the neighboring pixels), therefore CNN operations do not dependent on the size of the input frame, which is a great asset. If you look at the code, the size of the input frame is not explicitly given (it is 'None' instead). I hope this code is useful. Best, Guillaume

**Comment by LeopoldPu** [comment]
> 
Your reply is very helpful. I really appreciate it.
